<?php { ?>

<div class="products-list-ame-info">
    <img src="<?php echo $this->getViewFileUrl('AmeDigital_AME::images/logo-ame.svg'); ?>" width="45">
    <span class="product-list-ame-text" style="color: #5f5f5f;"> receba</span>
    <span class="product-list-ame-value" style="color: #f6235e; font-size: 15px">
        R$<?php echo number_format($block->getCashbackValue(),2,",","."); ?>
    </span>
    <span class="product-list-ame-text" style="color: #1b0487;">
        (<?php echo $block->getCashbackPercent(); ?>% de volta)
    </span>
</div>
<?php } ?>